config/routes.rb
ClinicDB::Application.routes.draw do
  resources :doctors

  resources :clinics

  

root :to => "clinics#index"
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  has_many :doctors, dependent: :destroy
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :clinic
  validates :clinic_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :set_clinic, only: [:show, :edit, :update, :destroy]

  # GET /clinics
  # GET /clinics.json
  def index
    @clinics = Clinic.order('id').all
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
    @doctors = Clinic.find(params[:id]).doctors.order('id').all
  end

  # GET /clinics/new
  def new
    @clinic = Clinic.new
  end

  # GET /clinics/1/edit
  def edit
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(clinic_params)

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic, notice: 'Clinic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @clinic }
      else
        format.html { render action: 'new' }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clinics/1
  # PATCH/PUT /clinics/1.json
  def update
    respond_to do |format|
      if @clinic.update(clinic_params)
        format.html { redirect_to @clinic, notice: 'Clinic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic.destroy
    respond_to do |format|
      format.html { redirect_to clinics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clinic_params
      params.require(:clinic).permit(:name)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.order('id').all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new()
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)
    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @doctor}
      else
        format.html { render action: 'new' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to @doctor.clinic }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :clinic_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/clinics/_form.html.erb
<%= form_for(@clinic) do |f| %>
  <% if @clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinic.errors.count, "error") %> prohibited this clinic from being saved:</h2>

      <ul>
      <% @clinic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clinics/edit.html.erb
<h1>Editing clinic</h1>

<%= render 'form' %>

<%= link_to 'Show', @clinic %> |
<%= link_to 'Back', clinics_path %>

app/views/clinics/index.html.erb
<h1>Listing Clinics</h1>

<table>
  <thead>
    <tr>
      <th> id</th>
      <th> name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clinics.each do |clinic| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= clinic.id %></td>
        <td><%= clinic.name %></td>
        <td><%= link_to 'Show', clinic %></td>
        <td><%= link_to 'Edit', edit_clinic_path(clinic) %></td>
        <td><%= link_to 'Destroy', clinic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clinic', new_clinic_path %>

app/views/clinics/new.html.erb
<h1>New clinic</h1>

<%= render 'form' %>

<%= link_to 'Back', clinics_path %>

app/views/clinics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> Clinic Name:</strong>
  <%= @clinic.name %>
</p>

<%= link_to 'Edit', edit_clinic_path(@clinic) %> |
<%= link_to 'Back', clinics_path %>

<p>
  <h1> List of Doctors: </h1>
</p>
<table>
  <thead>
    <tr>
      <th> id</th>
      <th> name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= doctor.id %></td>
        <td><%= doctor.name %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor, :clinic_id=>@clinic.id) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Doctor', new_doctor_path(:clinic_id=>@clinic.id) %>

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <%= f.hidden_field :clinic_id, :value => params[:clinic_id] %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', @doctor.clinic %>

app/views/doctors/index.html.erb
<h1>Listing doctors</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Clinic_ID</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.id %></td>
        <td><%= doctor.name %></td>
        <td><%= doctor.clinic_id %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/doctors/new.html.erb
<h1>New doctor</h1>
<%= render 'form' %>

<%= link_to 'Back', clinics_path+"/"+(params[:clinic_id]) %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doctor Name:</strong>
  <%= @doctor.name %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor, :clinic_id=>@doctor.clinic_id) %> |
<%= link_to 'Back', @doctor.clinic %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClinicDB</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

<%= yield %>

</body>
</html>